### PR TITLE
Proposal for aggregate initialization model

### PR DESCRIPTION
**Pull request by vuoriv**
Proposal for aggregate initialization model

Problem with currrent one
- State can be updated by implementing class
- Importance of first event can easilly ignored and initial state is setted manually (without event) which might leads to problems

Changes
- State modification can be done only privately
- Aggregate state initialization is left to user: first event must initialize state without accessing the state. 
   - Initialization can be done in **constructor** or **builder**.
   - **Exception is thrown** if state is used before initialization event
- Construction type is added to aggregate (NEW, EVENT_RECONSTRUCTED, STATE_CONSTRUCTED)
- `getState()` removed and state is now `lateinit` property with private setter and protected getter - more Kotlin like

Examples
- Constuctor initialization: https://github.com/nemit/paju-ddd/blob/alternative-initialization/ddd-core/src/test/kotlin/io/paju/ddd/AggregateRootTest.kt#L10
- Builder initialization: https://github.com/nemit/paju-ddd/blob/alternative-initialization/ddd-core/src/test/kotlin/io/paju/ddd/AggregateRootTest.kt#L18

**NOTE:** this is not compatible with older version and breaks existing code.

### CODE REVIEW

**Comment by fbjon** [comment]
Replying to self: it would probably cause problems with sealed subclasses (?), which would be a worse problem.

**Comment by vuoriv** [comment]
> One thought: that the state might be null even though it's non-nullable is a bit of a loophole for bugs to creep through, but I don't know how to resolve that.

@fbjon This is where i struggle big time and i do not have solution for it. Now it will throw exception if state is used wrong and misuse should be come visible early as possible. 

We can build more visible internal state and deny all wrong usage of aggregate, but not sure if it worth of doing at this point and result is still allmost same than it is now. Also, this can be done later if we need it.

I tried to force initEvent in constructor and it helps littlebit, but after this aggregate is not so flexible to use that this one is. 

----
Anyway, i tried this model with payment aggregate and it working quite nicely there.

**Comment by vuoriv** [comment]
@fbjon What problems did you have? I managed to add that function without problems. Thanks for working implementation 👍 

> The state of the aggregate is no longer verified in the example, is this intentional?

**Comment by fbjon** [comment]
> State has not been verified in SalesOrder ever.

Sorry! I was indeed confusing this with nemit/paju-billing#6 😅 
> What problems did you have?

I tried to do `protected fun stateIsInitialized()` in the AggregateRoot, but the compiler complains that it cannot infer the visibility in `SalesOrder`. It seems like a reasonable thing to do, but maybe it's against the language spec. Right now the method seems to be public regardless of the `StateExposed` interface, but it's probably not a problem anyway.

**Comment by vuoriv** [comment]
> I tried to do protected fun stateIsInitialized()

@fbjon True, i accidentally left it public. But after little rethinking: renamed `stateIsInitialized()` -> `isInitialized()` to indicate is aggregate ready or not. And also i think it is good to be public.

**Comment by vuoriv** [comment]
@kimmoeklund Thanks for comments

- Construction type is now internal
- Also tried simplify aggregate internally by removing `protected fun applyChange(event: E, isNew: Boolen)` fuction

**Pull request merged**
